export const FETCH_DRIVER_DETAILS = 'fetchDriverDetails'
export const FETCH_VEHICLE_DETAILS = 'fetchVehicleDetails'
export const FETCH_FUEL_HISTORY = 'fetchFuelHistory'
export const FETCH_MAINTENANCE_HISTORY = 'fetchMaintenanceHistory'
export const FETCH_INVOICE_HISTORY = 'fetchInvoiceHistory'
export const FETCH_LICENSING_HISTORY = 'fetchLicensingHistory'
export const FETCH_ACCIDENT_HISTORY = 'fetchAccidentHistory'
export const FETCH_RENTAL_HISTORY = 'fetchRentalHistory'
