export const SET_DRIVER_DETAILS = 'setDriverDetails'
export const SET_VEHICLE_DETAILS = 'setVehicleDetails'
export const SET_FUEL_HISTORY = 'setFuelHistory'
export const SET_MAINTENANCE_HISTORY = 'setMaintenanceHistory'
export const SET_INVOICE_HISTORY = 'setInvoiceHistory'
export const SET_LICENSING_HISTORY = 'setLicensingHistory'
export const SET_ACCIDENT_HISTORY = 'setAccidentHistory'
export const SET_RENTAL_HISTORY = 'setRentalHistory'
